import Head from 'next/head'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.Home}>
      <h1>Bienvenue sur mon blog</h1>
      <div className={styles.Description}>
        Je suis Jean-Baptiste, développeur Web reconverti. Je viens de terminer ma formation Intégrateur / Développeur Web chez OpenClassRooms.
        <br/>
        Je souhaite ouvrir ce blog afin de poster ici régulièrement mon avancement dans ma nouvelle vie de développeur web. 
      </div>
      </main>
    </>
  )
}
